---
- name: Install base packages
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  tags: packages

- name: Upgrade pip
  pip:
    name: pip
    state: latest
  tags: packages

- name: Install python for docker
  pip:
    name: docker
  tags: packages